### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by GamerMJay** [David-pm-pl/BetterCapes#1]
Hey, I have an idea, it would be cool if you could give each cape a permission 
example:
bettercapes.blue.cap

Otherwise you can currently choose any cape with the permission

**Comment by 0xliam627** [comment]
Next version

**Comment by GamerMJay** [comment]
😁👍

**Comment by dadevguy** [comment]
Same I Also Want This Feature + Custom Capes

**Comment by 0xliam627** [comment]
Dear @GamerMJay,
> Your suggestion has been accepted.
BetterCapes v0.0.2 has added this features please download [it here](https://github.com/David-pm-pl/BetterCapes/releases/tag/v0.0.2)
