### ISSUE TITLE
Issue crashes 

### ISSUE THREAD

**Issue by iTzAndrew33212** [David-pm-pl/BetterCapes#2]
Hi there

When i type the /bettercapes Red, server crashes.. Error code

Jul 10 08:41 [Server] EMERGENCY An unrecoverable error has occurred and the server has crashed. Creating a crash dump
Jul 10 08:41 [Server] INFO --- End of exception information ---
Jul 10 08:41 [Server] INFO #17 pmsrc(11): require(string[94] phar:///jar/pocketmine/pmmp/1.20.0/pmmp5/PocketMine-MP.phar/src/)
Jul 10 08:41 [Server] INFO #16 pmsrc/src/PocketMine(357): pocketmine\server()
Jul 10 08:41 [Server] INFO #15 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string[36] /, string[44] /plugins/)
Jul 10 08:41 [Server] INFO #14 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor()
Jul 10 08:41 [Server] INFO #13 pmsrc/src/Server(1674): pocketmine\snooze\SleeperHandler->sleepUntil(float 1688974914.2436)
Jul 10 08:41 [Server] INFO #12 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
Jul 10 08:41 [Server] INFO #11 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
Jul 10 08:41 [Server] INFO #10 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
Jul 10 08:41 [Server] INFO #9 pmsrc/src/network/mcpe/raklib/RakLibInterface(109): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#187807)
Jul 10 08:41 [Server] INFO #8 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[50] ..8H....'.}...........S.(..uiKT.......M}.$.C..P...)
Jul 10 08:41 [Server] INFO #7 pmsrc/src/network/mcpe/raklib/RakLibInterface(217): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[41] S...OJ-)I-JN,H-V.JMa.t..4..5....%Y.".....)
Jul 10 08:41 [Server] INFO #6 pmsrc/src/network/mcpe/NetworkSession(381): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\CommandRequestPacket#86559, string[38] M./bettercapes Red..@.Q1.......j.....D)
Jul 10 08:41 [Server] INFO #5 pmsrc/src/network/mcpe/NetworkSession(437): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#128095)
Jul 10 08:41 [Server] INFO #4 pmsrc/vendor/pocketmine/bedrock-protocol/src/CommandRequestPacket(55): pocketmine\network\mcpe\handler\InGamePacketHandler->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket#86559)
Jul 10 08:41 [Server] INFO #3 pmsrc/src/network/mcpe/handler/InGamePacketHandler(818): pocketmine\player\Player->chat(string[16] /bettercapes Red)
Jul 10 08:41 [Server] INFO #2 pmsrc/src/player/Player(1503): pocketmine\Server->dispatchCommand(object pocketmine\player\Player#138782, string[15] bettercapes Red)
Jul 10 08:41 [Server] INFO #1 pmsrc/src/Server(1415): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\player\Player#138782, string[15] bettercapes Red)
Jul 10 08:41 [Server] INFO #0 pmsrc/src/command/SimpleCommandMap(212): DavidGlitch04\BetterCapes\command\Capes->execute(object pocketmine\player\Player#138782, string[11] bettercapes, array[1])
Jul 10 08:41 [Server] INFO --- Stack trace ---
Jul 10 08:41 [Server] CRITICAL Error: "Call to undefined function imagecreatefrompng()" (EXCEPTION) in "plugins/BetterCapes_dev-16.phar/src/command/Capes" at line 102
Jul 10 08:41 [Server] EMERGENCY Crash occurred while handling a packet from session: EmpireBoss007

Take care
Andrew

**Comment by 0xliam627** [comment]
Provide platform name, pocketmine api, BetterCapes version!

**Comment by iTzAndrew33212** [comment]
platform name as in the hosting ? (virtualgladiators) or android (device I'm playing on) , api 5.2.0, BetterCapes version - 0.0.4

**Comment by taylordevs** [comment]
try `sudo apt-get install php-gd`

**Comment by 0xliam627** [comment]
I think the platform was missing that function completely unrelated to `BetterCapes`, refer [here](https://stackoverflow.com/questions/13338339/imagecreatefromjpeg-and-similar-functions-are-not-working-in-php)
